### ISSUE TITLE
Overwrites the entire line

### ISSUE THREAD

**Issue by traumturbulenzen** [ricardo118/grav-plugin-colorbuttons#3]
Super extension. Goes well if you know how to handle it. It is the case that when I select and cut out a text and then use the editor button, the entire line is colored. A clear definition of the text cut would be super cool.

Two screenshots are attached.
![Screenshot from 2020-04-17 00-18-27](https://user-images.githubusercontent.com/18284142/79512155-1e6e5c00-8041-11ea-8926-8dae0b9e44f7.png)
![Screenshot from 2020-04-17 00-18-42](https://user-images.githubusercontent.com/18284142/79512495-d56ad780-8041-11ea-8871-1364feb1e6e4.png)

**Comment by ricardo118** [comment]
oh i see whats happening. it may have recently broken. thank you ill check it out

**Comment by ricardo118** [comment]
@traumturbulenzen i pushed an updated and its fixed now. You can now select an area to wrap the shortcode or you can have no selection and it will do the whole paragraph/line
